name: Iris_Project_Conda_Environment
#Execution code: conda env create -f configuration/irisproject_conda_env.yaml
channels:
 - defaults

dependencies:
 - python=3.9.12
 - pandas=1.4.2
 - markupsafe=2.0.0
 - scikit-learn=1.0.2
 - pip:
    - pandas-profiling==3.2.0
    - matplotlib==3.5.2
    - numpy==1.23
