model_name: irisdata_classification_model.sav
dataset_name: irisdata_raw.csv
iris_analysis_report_name: irisreport.html
encoder_mappings: encoder_mapping.npy

column_names: ["sepal length","sepal width","petal length","petal width","class"]
features: ["sepal length","sepal width","petal length","petal width"]
label_name: 'class'

cmd_arguments:
  options: "g"
  long_options: ["graphs"]

decisiontree_settings:
 criterion: entropy

kfold_settings:
 nr_splits: 5
 shuffle: True
 random_state: 123

report_settings:
  title: "Iris Data Profile Report"

#Sepal Length, Sepal Width, Petal Length, Petal Width
input_min_values: [4.3,2,1,0.1]

#Sepal Length, Sepal Width, Petal Length, Petal Width
input_max_values: [7.9,4.4,6.9,2.5]