
file_paths:
  model_path: models/irisdata_classification_model.sav
  dataset_path: source/data/irisdata_raw.csv
  iris_analysis_report_path: reports/irisreport.html
  encoder_mappings: source/data/encoder_mapping.pkl

column_names: ["sepal length","sepal width","petal length","petal width","class"]

decisiontree_settings:
 criterion: entropy

kfold_settings:
 nr_splits: 5
 shuffle: True
 random_state: 123

#Sepal Length, Sepal Width, Petal Length, Petal Width
input_min_values: [4.3,2,1,0.1]

#Sepal Length, Sepal Width, Petal Length, Petal Width
input_max_values: [7.9,4.4,6.9,2.5]